change to pydantic 2.7.4 to fix installation error on latest python
"/Users/runner/.cache/uv/sdists-v9/pypi/pydantic-core/2.16.3/XwDpeHzgHWi0908hXhToH/src/generate_self_schema.py",
      line 195, in eval_forward_ref
            return type_._evaluate(core_schema.__dict__, None)
                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        TypeError: ForwardRef._evaluate() missing 1 required keyword-only
      argument: 'recursive_guard'